/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_tish_embedded;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.connector.Connector;
import org.apache.catalina.startup.Tomcat;
import org.apache.coyote.http11.Http11Nio2Protocol;
import org.quartz.Scheduler;
import org.quartz.SchedulerFactory;
import org.quartz.impl.StdSchedulerFactory;

import ReminderAPI.Reminder;
import Utilities.QuartzReminder;
import repositories.PostgreAdapter;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

public class App {
    public static Properties prop;
    public static Reminder reminder;
    public static void main(String[] args) throws Exception {
        reminder = new QuartzReminder(new PostgreAdapter());
        easyMain(args);
    }
    public static void easyMain(String[] args)
            throws Exception {

        // initialize scheduler
        SchedulerFactory schedulerFactory = new StdSchedulerFactory();

        
        Tomcat tomcat = new Tomcat();

        prop = new Properties();
        String fileName = "./src/main/resources/app.properties";
        FileInputStream fis = new FileInputStream(fileName);
        prop.load(fis);

        int port = Integer.parseInt(prop.getProperty("port"));
        String hostname = App.prop.getProperty("hostname");
        String keyStorePass = App.prop.getProperty("keyStorePass");
        tomcat.setHostname(hostname);

        // idk why we need this connector, maybe for connecting via http?
        System.out.println(System.getProperty("user.dir"));
        Http11Nio2Protocol protocolHandler = new Http11Nio2Protocol();
        protocolHandler.setPort(port);
        protocolHandler.setSSLEnabled(true);
        // protocolHandler.setSSL(true);
        protocolHandler.setKeystoreFile("../src/main/resources/demoKey");
        protocolHandler.setKeystorePass(keyStorePass);
        protocolHandler.setKeyAlias("mykey");
        // protocolHandler.setSSLVerifyClient(Boolean.toString(true));
        System.out.println(protocolHandler.isSSLEnabled());
        Connector conn = new Connector(protocolHandler);
        tomcat.setConnector(conn);


        Context ctx = tomcat.addWebapp("", new File("./src/main/resources").getAbsolutePath());
        // by default jndi is disabled in tomcat embedded
        tomcat.enableNaming();



        
        tomcat.start();
        tomcat.getServer().await();
    }
 
}
