/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_tish_embedded;

import org.apache.catalina.Context;
import org.apache.catalina.WebResource;
import org.apache.catalina.WebResourceRoot;
import org.apache.catalina.WebResourceSet;
import org.apache.catalina.connector.Connector;
import org.apache.catalina.core.StandardContext;
import org.apache.catalina.startup.Tomcat;
import org.apache.coyote.http11.Http11Nio2Protocol;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileInputStream;
import java.util.Properties;


//  this is the main class, which is responsible for starting Tomcat server
public class BackendApp {
    public static Properties prop;
    static Logger logger = LoggerFactory.getLogger(BackendApp.class);
    // this will be called when the program start
    public static void main(String[] args) throws Exception {
        logger.info("hello there");
        easyMain(args);
    }
    
    /** 
     * @param args
     * @throws Exception
     */
    public static void easyMain(String[] args)
            throws Exception {
        Tomcat tomcat = new Tomcat();
        prop = new Properties();
        String fileName = "./src/main/resources/app.properties";
        FileInputStream fis = new FileInputStream(fileName);
        prop.load(fis);
        // fix the way we retrieve resource 
        // logger.info("xd {}",Properties.class.getResource("app.properties"));

        int port = Integer.parseInt(prop.getProperty("port"));
        String hostname = BackendApp.prop.getProperty("hostname");
        String keyStorePass = BackendApp.prop.getProperty("keyStorePass");
        String keyStoreName = BackendApp.prop.getProperty("keyStoreName");
        tomcat.setHostname(hostname);
        // idk why we need this connector, maybe for connecting via http?
        System.out.println(System.getProperty("user.dir"));
        Http11Nio2Protocol protocolHandler = new Http11Nio2Protocol();
        protocolHandler.setPort(port);
        protocolHandler.setSSLEnabled(true);
        // protocolHandler.setSSL(true);
        protocolHandler.setKeystoreFile("../src/main/resources/"+keyStoreName);
        protocolHandler.setKeystorePass(keyStorePass);
        protocolHandler.setKeyAlias("mykey");
        protocolHandler.setSSLVerifyClient(Boolean.toString(true));
        
        System.out.println(protocolHandler.isSSLEnabled());
        Connector conn = new Connector(protocolHandler);
        tomcat.setConnector(conn);

        Context ctx = tomcat.addWebapp("", new File("./src/main/resources").getAbsolutePath());

        // by default jndi is disabled in tomcat embedded
        tomcat.enableNaming();

        // set config file for ctx must be done first be4 being registered to the virtual host
        // the minor difference between addWebapp and addContext is addWebApp also 
        // include a context.xml and web.xml while addContext doesnt

                tomcat.start();
        tomcat.getServer().await();
    }

 
}
