/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_tish_embedded;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        BackendApp classUnderTest = new BackendApp();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
